/** Public Monday board config — board/column IDs only, never API keys */
export const MONDAY_BOARD = {
  boardId: 18430342548,
  workspaceId: 15837288,
  workspaceName: 'טיול ליפן ותאילנד',
  boardUrl: 'https://shahar-monday.monday.com/boards/18430342548',
  tokensUrl: 'https://shahar-monday.monday.com/apps/manage/tokens',
  columns: {
    record_type: 'color_mm71prpy',
    country: 'dropdown_mm71mrfx',
    city: 'dropdown_mm71e1b4',
    day_number: 'numeric_mm71hpdc',
    date: 'text_mm71sywf',
    weekday: 'text_mm715dph',
    title: 'text_mm71tdvy',
    weather: 'text_mm71ed5f',
    hotel: 'text_mm71z43e',
    time: 'text_mm71vjzz',
    time_end: 'text_mm71m5qe',
    desc: 'long_text_mm71h6jw',
    lat: 'numeric_mm71vmzv',
    lng: 'numeric_mm715zkm',
    place_type: 'color_mm71sgxx',
    sort_order: 'numeric_mm71kjfp',
    area: 'text_mm713pt0',
    category: 'dropdown_mm71zaam',
    food_day: 'numeric_mm713zc3',
  },
  recordTypes: { day: 'Day', activity: 'Activity', food: 'Food' },
  countries: { japan: 'Japan', thailand: 'Thailand' },
  /** Status labels on place_type column (must match board / create_labels_if_missing) */
  placeTypes: {
    attraction: { value: 'attraction', label: '🏛️ אטרקציה' },
    cafe: { value: 'cafe', label: '☕ בית קפה' },
    restaurant: { value: 'restaurant', label: '🍽️ מסעדה' },
  },
};
